### ISSUE TITLE
Doesn't process assignments data, only applications?

### ISSUE THREAD

**Issue by ThomasHeliase** [USPTO/TrademarkPublicData#4]
From a a few brief tests it appears the splitter is only working for applications `'apc*.zip|xml'` not for trademark assignment `'asb*.zip|xml'`?  

It's a little confusing, since the README lists both application and assignment files (implying both types can be processed) - however it is clear only application files are used in any of the in-line examples.  

Before I fork off  :) and try to fix the issue - should the current version work on assignment data as well?

**Comment by hendersonmichael** [comment]
Yes that is correct. The splitter currently supports the TM annual and daily application files. 
The links to the bulk down loadable assignment files in the README were there only as a reference but have been removed to avoid any confusion.
